name: game_launcher
description: A PC game launcher with artwork display.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.8.3
  video_player: ^2.7.0
  chewie: ^1.7.0
  path_provider: ^2.1.0
  process_run: ^0.13.1
  media_kit: ^1.1.11
  media_kit_video: ^1.2.5
  media_kit_libs_windows_video: ^1.0.10
  media_kit_native_event_loop: ^1.0.8  # Added to fix event loop warning
  provider: ^6.1.1
  window_manager: ^0.3.7
  shared_preferences: ^2.2.3
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true